import { Link } from 'react-router-dom'

const productDecisions = [
  {
    decision: 'AI Model',
    choice: 'Google Gemini 2.5 Flash Lite',
    why: 'Significantly cheaper than GPT or Claude, with comparable story quality and 4–6 second response times vs. 20–30 seconds with other models. Speed matters for a child waiting for their story.',
  },
  {
    decision: 'Database',
    choice: 'SQLite',
    why: 'Lightweight and zero-infrastructure for a local-first MVP. No server to spin up, no cost, no overhead — the right call for this stage of the product.',
  },
  {
    decision: 'Authentication',
    choice: 'JWT + argon2id',
    why: "Parents need secure accounts to manage their child's profile and preferences. Auth wasn't optional — it's what makes the experience personal and safe.",
  },
  {
    decision: 'Metrics Dashboard',
    choice: 'Intentionally deferred',
    why: 'Built the scaffold, but chose not to populate it until there are real users generating real data. Vanity metrics at zero users waste build time.',
  },
]

const roadmapItems = [
  {
    number: '01',
    title: 'Analytics Dashboard',
    body: 'Build out the metrics dashboard with real story generation data, error rates, and usage patterns.',
  },
  {
    number: '02',
    title: 'Voice Narration',
    body: 'Add text-to-speech so the app reads the story aloud, turning it into a true hands-free bedtime experience.',
  },
  {
    number: '03',
    title: 'Story Illustrations',
    body: 'Illustration prompts are already being generated by Gemini — the next step is rendering them as actual images so every story has its own unique artwork.',
  },
  {
    number: '04',
    title: 'Push Notifications',
    body: 'Remind parents at bedtime that tonight\'s story is ready to generate — reducing drop-off and building a consistent bedtime ritual.',
  },
  {
    number: '05',
    title: 'Story Sharing',
    body: 'Let parents share a story link with grandparents or family members so the magic doesn\'t stay in one household.',
  },
  {
    number: '06',
    title: 'Story Themes & Packs',
    body: 'Seasonal and themed content packs — Halloween, Christmas, back to school — giving kids something to look forward to throughout the year.',
  },
  {
    number: '07',
    title: 'Family Plan',
    body: 'One account, multiple parent logins — built for families where both parents want access without sharing credentials.',
  },
]

const pmLearnings = [
  {
    label: '01',
    heading: 'Vibe-coding is a real PM skill.',
    body: "I built this without writing a single line of code — but every meaningful decision (model choice, auth, scope, what not to build) was a product decision, not a technical one.",
  },
  {
    label: '02',
    heading: 'A strong PRD is the foundation.',
    body: "The quality of what Claude Code produced was directly proportional to how clearly I specified the problem upfront. Garbage in, garbage out — even with AI.",
  },
  {
    label: '03',
    heading: "LLMs are infrastructure, not magic.",
    body: "Connecting Gemini via API reframed how I think about AI — it's a callable service that solves a specific problem, not a chatbot.",
  },
  {
    label: '04',
    heading: "Shipping teaches you things specs don't.",
    body: "Running the app locally, pushing to GitHub, managing environment variables — doing it demystified the development process in a way no course could.",
  },
  {
    label: '05',
    heading: "Trade-offs don't disappear just because AI writes the code.",
    body: "Choosing Gemini over Claude wasn't a technical call — it was a cost, speed, and UX decision. That's always a PM's job.",
  },
]

export default function DreamyTime() {
  return (
    <div className="animate-page-in pt-24 min-h-screen px-6 md:px-12 max-w-7xl mx-auto">

      {/* Back */}
      <div className="pt-10 mb-20">
        <Link
          to="/"
          className="font-mono text-xs tracking-widest uppercase text-[#4A4A4A] hover:text-[#8B6914] transition-colors duration-200 flex items-center gap-2"
        >
          <span>←</span> Back to Work
        </Link>
      </div>

      {/* Header */}
      <div className="border-t border-warm-gray pt-14 grid md:grid-cols-12 gap-10">
        <div className="md:col-span-3 flex flex-col gap-3">
          <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914]">02</span>
          <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80">
            Solo · Vibe-Coding
          </span>
          <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80">
            Side Project
          </span>
        </div>

        <div className="md:col-span-9">
          <h1
            className="font-display font-bold text-charcoal leading-[0.9] mb-6"
            style={{ fontSize: 'clamp(36px, 8vw, 110px)' }}
          >
            Dreamy Tales
            <br />
            <span className="font-light italic">Storyteller</span>
          </h1>
          <p className="font-display text-xl md:text-2xl italic text-charcoal/75 leading-relaxed max-w-xl">
            A generative bedtime story app built at the intersection of AI and imaginative play.
          </p>
        </div>
      </div>

      {/* ── 01 PROBLEM ─────────────────────────────────── */}
      <div className="mt-24 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">01</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Problem</span>
        <h2
          className="font-display font-bold text-charcoal leading-tight mb-3"
          style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
        >
          A Different Story, Every Single Night
        </h2>
        <p className="font-display italic text-charcoal/75 text-lg mb-6">
          Bedtime shouldn't be a creative emergency.
        </p>
        <p className="text-charcoal/85 text-base leading-relaxed max-w-2xl">
          Parents love reading to their kids — but coming up with a fresh, engaging story every night is exhausting. Dreamy Tales generates unlimited, age-appropriate bedtime stories on demand, so the magic never runs out.
        </p>
      </div>

      {/* ── 02 TARGET AUDIENCE ─────────────────────────── */}
      <div className="mt-20 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">02</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Target Audience</span>
        <h2
          className="font-display font-bold text-charcoal leading-tight mb-3"
          style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
        >
          Built for Busy Parents Who Still Show Up
        </h2>
        <p className="font-display italic text-charcoal/75 text-lg mb-6">
          You want the moment. You just need the story.
        </p>
        <p className="text-charcoal/85 text-base leading-relaxed max-w-2xl mb-5">
          Dreamy Tales is designed for parents of children ages 3–10 who value quality bedtime rituals but don't always have the bandwidth to improvise. It removes the creative lift so the connection can stay front and centre.
        </p>
        <p className="text-charcoal/85 text-base leading-relaxed max-w-2xl mb-5">
          Kids get bored of the same stories — and parents know it. Dreamy Tales generates something new every night, so there's always a reason to look forward to bedtime.
        </p>
        <p className="text-charcoal/85 text-base leading-relaxed max-w-2xl">
          Books are expensive. And as kids grow, so does the cost — a new reading level means a new shelf of books. With Dreamy Tales, the stories grow as they do. No new purchases. No outgrown shelves. Just stories that meet them where they are.
        </p>
      </div>

      {/* ── 03 PRODUCT DECISIONS ───────────────────────── */}
      <div className="mt-20 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">03</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Product Decisions</span>
        <h2
          className="font-display font-bold text-charcoal leading-tight mb-8"
          style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
        >
          Product Decisions
        </h2>
        {/* Table header */}
        <div className="hidden md:grid grid-cols-[1fr_1.5fr_2.5fr] gap-4 border-b border-warm-gray pb-3 mb-2">
          <span className="font-mono text-[10px] tracking-widest uppercase text-charcoal/65">Decision</span>
          <span className="font-mono text-[10px] tracking-widest uppercase text-charcoal/65">What I Chose</span>
          <span className="font-mono text-[10px] tracking-widest uppercase text-charcoal/65">Why It Mattered</span>
        </div>
        {productDecisions.map((row) => (
          <div key={row.decision} className="grid md:grid-cols-[1fr_1.5fr_2.5fr] gap-4 border-b border-warm-gray py-5">
            <p className="font-mono text-xs tracking-wide text-[#8B6914] uppercase">{row.decision}</p>
            <p className="text-charcoal text-sm font-medium leading-snug">{row.choice}</p>
            <p className="text-charcoal/80 text-sm leading-relaxed">{row.why}</p>
          </div>
        ))}
      </div>

      {/* ── 04 ARCHITECTURE OVERVIEW ───────────────────── */}
      <div className="mt-20 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">04</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Architecture</span>
        <h2
          className="font-display font-bold text-charcoal leading-tight mb-6"
          style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
        >
          Architecture Overview
        </h2>
        <p className="text-charcoal/85 text-base leading-relaxed max-w-2xl mb-8">
          Dreamy Tales is built as a full-stack monorepo with a React + Vite
          frontend and an Express API backend, deployed across Vercel (frontend)
          and Railway (backend + database). Stories are generated in real time
          using Google Gemini 2.5 Flash Lite, streamed to the client via
          Server-Sent Events (SSE) so there's no waiting on a loading screen.
          Parent accounts are secured with JWT authentication and Argon2id
          password hashing, with each child profile scoped to its parent. Data
          persists in a Railway-managed PostgreSQL database — chosen over the
          original SQLite setup to survive redeployments and support proper
          connection pooling as the product scales.
        </p>
        <iframe
          src="/dreamyTales_arch.html"
          title="Dreamy Tales Architecture Overview"
          className="w-full rounded-lg border border-[#C9A96E]/20"
          style={{ height: '800px' }}
        />
      </div>

      {/* ── 05 ROADMAP ─────────────────────────────────── */}
      <div className="mt-20 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">05</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Roadmap</span>
        <div className="flex items-center gap-4 mb-8">
          <h2
            className="font-display font-bold text-charcoal leading-tight"
            style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
          >
            What's Next
          </h2>
          <span className="font-mono text-[9px] tracking-widest uppercase border border-[#8B6914] text-[#8B6914] bg-[#8B6914]/10 px-2 py-1">
            Roadmap
          </span>
        </div>
        <div className="space-y-0">
          {roadmapItems.map((item) => (
            <div key={item.number} className="border-t border-warm-gray py-6 grid md:grid-cols-12 gap-4">
              <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] md:col-span-1">{item.number}</span>
              <div className="md:col-span-11">
                <p className="font-display font-semibold text-charcoal text-lg mb-1">{item.title}</p>
                <p className="text-charcoal/80 text-sm leading-relaxed">{item.body}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── 06 TRY IT OUT ──────────────────────────────── */}
      <div className="mt-20 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">06</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Try It Out</span>
        <h2
          className="font-display font-bold text-charcoal leading-tight mb-4"
          style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
        >
          Try It Out
        </h2>
        <p className="text-charcoal/85 text-base leading-relaxed max-w-xl mb-8">
          Try Dreamy Tales right here — create an account, add a child profile,
          and generate your first story.
        </p>
        <iframe
          src="https://dreamy-tales-web.vercel.app/"
          title="Dreamy Tales App"
          className="rounded-lg border border-[#C9A96E]/20 mb-8"
          style={{ height: '850px', width: '400px', display: 'block', margin: '0 auto' }}
          allow="same-origin"
        />
        <a
          href="https://github.com/davicapersaud/dreamy-tales"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 border border-charcoal/30 text-charcoal hover:border-[#8B6914] hover:text-[#8B6914] transition-colors duration-200 px-5 py-3 font-mono text-xs tracking-widest uppercase"
        >
          View on GitHub →
        </a>
      </div>

      {/* ── 07 WHAT I LEARNED AS A PM ──────────────────── */}
      <div className="mt-20 mb-32 border-t border-warm-gray pt-14">
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] block mb-1">07</span>
        <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-charcoal/80 block mb-6">Reflections</span>
        <h2
          className="font-display font-bold text-charcoal leading-tight mb-10"
          style={{ fontSize: 'clamp(24px, 4vw, 48px)' }}
        >
          What I Learned as a PM Building This
        </h2>
        <div className="space-y-0">
          {pmLearnings.map((item) => (
            <div key={item.label} className="border-t border-warm-gray py-6 grid md:grid-cols-12 gap-4">
              <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#8B6914] md:col-span-1">{item.label}</span>
              <div className="md:col-span-11">
                <p className="font-display font-semibold text-charcoal text-lg mb-2">{item.heading}</p>
                <p className="text-charcoal/80 text-sm leading-relaxed">{item.body}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

    </div>
  )
}
